const AUTO_DETECT_ERROR_MESSAGE = "Không thể tự động nhận diện ngôn ngữ nguồn.";
const TRANSLATE_JOB_POLL_INTERVAL_MS = 600;
const TRANSLATE_PROGRESS_STEP_DELAY_MS = 12;

export {
  AUTO_DETECT_ERROR_MESSAGE,
  TRANSLATE_JOB_POLL_INTERVAL_MS,
  TRANSLATE_PROGRESS_STEP_DELAY_MS,
};
